import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { User, DollarSign, Bell, Shield, Monitor } from 'lucide-react';
import { Card } from '../components/ui/Card';
import { Input } from '../components/ui/Input';
import { Button } from '../components/ui/Button';
export const Settings = () => {
    return (_jsxs(motion.div, { initial: { opacity: 0, y: 10 }, animate: { opacity: 1, y: 0 }, className: "flex flex-col lg:flex-row gap-8 max-w-6xl mx-auto", children: [_jsxs("div", { className: "w-full lg:w-64 flex flex-col gap-2", children: [_jsx("h2", { className: "text-xl font-bold text-text-primary mb-4 px-3", children: "Settings" }), [
                        { id: 'profile', label: 'Profile', icon: User, active: true },
                        { id: 'billing', label: 'Rates & Billing', icon: DollarSign, active: false },
                        { id: 'notifications', label: 'Notifications', icon: Bell, active: false },
                        { id: 'security', label: 'Security', icon: Shield, active: false },
                        { id: 'preferences', label: 'Preferences', icon: Monitor, active: false },
                    ].map((item) => (_jsxs("button", { className: `flex items-center gap-3 px-4 py-2.5 rounded-lg text-sm font-medium transition-colors ${item.active ? 'bg-accent/10 text-accent' : 'text-text-secondary hover:text-text-primary hover:bg-surface-light'}`, children: [_jsx(item.icon, { className: "w-4 h-4" }), item.label] }, item.id)))] }), _jsxs("div", { className: "flex-1 flex flex-col gap-8", children: [_jsxs(Card, { className: "p-6 md:p-8 flex flex-col gap-8", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-lg font-semibold text-text-primary mb-1", children: "Profile Information" }), _jsx("p", { className: "text-sm text-text-muted", children: "Update your account details and public profile." })] }), _jsxs("div", { className: "flex items-center gap-6", children: [_jsx("div", { className: "w-20 h-20 rounded-full bg-gradient-to-br from-accent to-purple-600 flex items-center justify-center text-white font-medium text-2xl shadow-lg", children: "JD" }), _jsxs("div", { className: "flex flex-col gap-2", children: [_jsx(Button, { variant: "secondary", size: "sm", children: "Change Avatar" }), _jsx("span", { className: "text-xs text-text-muted", children: "JPG, GIF or PNG. Max size of 800K" })] })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsx(Input, { label: "First Name", defaultValue: "John" }), _jsx(Input, { label: "Last Name", defaultValue: "Doe" }), _jsx(Input, { label: "Email Address", type: "email", defaultValue: "john@chronos.app", className: "md:col-span-2" }), _jsx(Input, { label: "Role / Title", defaultValue: "Lead Designer", className: "md:col-span-2" })] })] }), _jsxs(Card, { className: "p-6 md:p-8 flex flex-col gap-8", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-lg font-semibold text-text-primary mb-1", children: "Rates & Billing" }), _jsx("p", { className: "text-sm text-text-muted", children: "Set your default hourly rate for billable projects." })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsx(Input, { label: "Default Hourly Rate (USD)", type: "number", defaultValue: "150", leftIcon: _jsx(DollarSign, { className: "w-4 h-4" }) }), _jsxs("div", { className: "flex flex-col gap-1.5 justify-end", children: [_jsx("label", { className: "text-sm font-medium text-text-secondary", children: "Currency" }), _jsxs("select", { className: "w-full bg-surface border border-border rounded-lg px-4 py-2 text-sm text-text-primary focus:outline-none focus:border-accent h-[38px]", children: [_jsx("option", { children: "USD ($)" }), _jsx("option", { children: "EUR (\u20AC)" }), _jsx("option", { children: "GBP (\u00A3)" })] })] })] })] }), _jsxs("div", { className: "flex justify-end gap-4", children: [_jsx(Button, { variant: "ghost", children: "Cancel" }), _jsx(Button, { children: "Save Changes" })] })] })] }));
};
